from datetime import datetime, timezone
from typing import Any


def build_trending_thread(trends: list[dict[str, Any]]) -> dict[str, str]:
    """Format a list of trending items into a Reddit post title and body."""
    date_text = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"Weekly Developer Trends — {date_text}"

    if not trends:
        return {
            "title": title,
            "body": "No significant trends discovered this week. Stay tuned!",
        }

    lines = ["Here are the top trending repositories this week:", ""]
    for item in trends:
        name = item.get("full_name", "Unknown")
        stars = item.get("stars", 0)
        desc = item.get("description") or "No description provided."
        url = item.get("url", "#")
        lines.append(f"### [{name}]({url})")
        lines.append(f"⭐ {stars} stars")
        lines.append(f"> {desc}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Lorapok Red Bot*")

    return {"title": title, "body": "\n".join(lines)}
